name: baby_subscription
description: BabySubscription - App de suscripción de pañales con alertas de stock bajo.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  crypto: ^3.0.6
  font_awesome_flutter: ^10.8.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
